"""order_transaction

Revision ID: 12f473313ba1
Revises: ebdef07b76ee
Create Date: 2025-07-22 08:35:55.895235

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '12f473313ba1'
down_revision: Union[str, None] = 'ebdef07b76ee'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_unique_constraint(None, 'order_transactions', ['order_id'])
    op.drop_constraint('order_transactions_order_id_fkey', 'order_transactions', type_='foreignkey')
    op.create_foreign_key(None, 'order_transactions', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_transactions', type_='foreignkey')
    op.create_foreign_key('order_transactions_order_id_fkey', 'order_transactions', 'orders', ['order_id'], ['id'])
    op.drop_constraint(None, 'order_transactions', type_='unique')
    # ### end Alembic commands ###
