"""update

Revision ID: 1f8fe613e5c9
Revises: 146dedfac3c7
Create Date: 2025-07-18 00:34:21.999514

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '1f8fe613e5c9'
down_revision: Union[str, None] = '146dedfac3c7'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mess_tables', 'qr_code_url')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mess_tables', sa.Column('qr_code_url', sa.VARCHAR(), autoincrement=False, nullable=True))
    # ### end Alembic commands ###
