"""opaque_token

Revision ID: 288e4a5d70f0
Revises: ef7cdb1cca17
Create Date: 2025-07-16 04:15:26.577104

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '288e4a5d70f0'
down_revision: Union[str, None] = 'ef7cdb1cca17'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('customer_session_token',
    sa.Column('id', sa.UUID(), nullable=False),
    sa.Column('mess_id', sa.UUID(), nullable=False),
    sa.Column('token', sa.String(), nullable=False),
    sa.ForeignKeyConstraint(['mess_id'], ['mess.id'], ondelete='cascade'),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('customer_session_token')
    # ### end Alembic commands ###
