"""mess_logo_currency_add

Revision ID: 2d8f7dcbede4
Revises: aff9c43ddef9
Create Date: 2025-06-22 16:51:49.537375

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '2d8f7dcbede4'
down_revision: Union[str, None] = 'aff9c43ddef9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mess', sa.Column('currency', sa.String(), nullable=True))
    op.add_column('mess', sa.Column('logo', sa.String(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('mess', 'logo')
    op.drop_column('mess', 'currency')
    # ### end Alembic commands ###
