"""orders_item_tweak

Revision ID: 33253043e39d
Revises: e1c606f67ab3
Create Date: 2025-07-21 02:55:58.103473

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '33253043e39d'
down_revision: Union[str, None] = 'e1c606f67ab3'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('order_items_order_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'orders', ['order_id'], ['id'], ondelete='CASCADE')
    op.alter_column('orders', 'table_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('orders_table_id_fkey', 'orders', type_='foreignkey')
    op.drop_constraint('orders_mess_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'mess', ['mess_id'], ['id'], ondelete='CASCADE')
    op.create_foreign_key(None, 'orders', 'mess_tables', ['table_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_mess_id_fkey', 'orders', 'mess', ['mess_id'], ['id'])
    op.create_foreign_key('orders_table_id_fkey', 'orders', 'mess_tables', ['table_id'], ['id'])
    op.alter_column('orders', 'table_id',
               existing_type=sa.UUID(),
               nullable=False)
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_order_id_fkey', 'order_items', 'orders', ['order_id'], ['id'])
    # ### end Alembic commands ###
