"""orders_relation_customer

Revision ID: 491e9835d9b2
Revises: 1b37c48afebf
Create Date: 2025-07-20 09:01:40.864201

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '491e9835d9b2'
down_revision: Union[str, None] = '1b37c48afebf'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('orders_customer_id_fkey', 'orders', type_='foreignkey')
    op.create_foreign_key(None, 'orders', 'customer', ['customer_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'orders', type_='foreignkey')
    op.create_foreign_key('orders_customer_id_fkey', 'orders', 'user', ['customer_id'], ['id'])
    # ### end Alembic commands ###
