"""mess user relation update 4

Revision ID: 5666c265422c
Revises: 0f8ec5468b10
Create Date: 2025-06-23 07:09:53.751403

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5666c265422c'
down_revision: Union[str, None] = '0f8ec5468b10'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('mess_customer',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('mess_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mess_id'], ['mess.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    op.create_table('mess_staff',
    sa.Column('user_id', sa.UUID(), nullable=True),
    sa.Column('mess_id', sa.UUID(), nullable=True),
    sa.ForeignKeyConstraint(['mess_id'], ['mess.id'], ),
    sa.ForeignKeyConstraint(['user_id'], ['user.id'], )
    )
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mess_staff')
    op.drop_table('mess_customer')
    # ### end Alembic commands ###
