"""order_transaction

Revision ID: 5fe8394cccae
Revises: 12f473313ba1
Create Date: 2025-07-22 08:43:33.319969

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '5fe8394cccae'
down_revision: Union[str, None] = '12f473313ba1'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_transactions', sa.Column('currency', sa.String(), nullable=False))
    op.add_column('order_transactions', sa.Column('payment_method', sa.Enum('CASH', 'ESEWA', 'KHALTI', 'STRIPE', name='paymentmethodenum'), nullable=False))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('order_transactions', 'payment_method')
    op.drop_column('order_transactions', 'currency')
    # ### end Alembic commands ###
