"""category_active_field

Revision ID: 74c3e22b30df
Revises: e167ab91be6e
Create Date: 2025-07-01 02:08:25.139476

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '74c3e22b30df'
down_revision: Union[str, None] = 'e167ab91be6e'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item_category', sa.Column('is_active', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item_category', 'is_active')
    # ### end Alembic commands ###
