"""orders_tweak

Revision ID: ad18cb2371be
Revises: 491e9835d9b2
Create Date: 2025-07-20 09:18:05.830274

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'ad18cb2371be'
down_revision: Union[str, None] = '491e9835d9b2'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('is_cancelled', sa.Boolean(), nullable=True))
    op.add_column('orders', sa.Column('has_added_items', sa.Boolean(), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('orders', 'has_added_items')
    op.drop_column('orders', 'is_cancelled')
    op.drop_column('order_items', 'is_cancelled')
    # ### end Alembic commands ###
