"""simplified_images_menu_items

Revision ID: bf50f11e2138
Revises: 74c3e22b30df
Create Date: 2025-07-05 19:02:56.921281

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'bf50f11e2138'
down_revision: Union[str, None] = '74c3e22b30df'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('menu_item_image')
    op.add_column('menu_item', sa.Column('primary_image', sa.String(), nullable=True))
    op.add_column('menu_item', sa.Column('images', sa.ARRAY(sa.String()), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('menu_item', 'images')
    op.drop_column('menu_item', 'primary_image')
    op.create_table('menu_item_image',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('is_primary', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('menu_item_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('url', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('path', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.ForeignKeyConstraint(['menu_item_id'], ['menu_item.id'], name='menu_item_image_menu_item_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='menu_item_image_pkey')
    )
    # ### end Alembic commands ###
