"""orders_tweak

Revision ID: c4449f54ab99
Revises: ad18cb2371be
Create Date: 2025-07-20 09:27:44.451209

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'c4449f54ab99'
down_revision: Union[str, None] = 'ad18cb2371be'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('total_price', sa.Integer(), nullable=False))
    op.drop_column('order_items', 'price')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_items', sa.Column('price', sa.INTEGER(), autoincrement=False, nullable=False))
    op.drop_column('order_items', 'total_price')
    # ### end Alembic commands ###
