"""ordertransaction_pid

Revision ID: d3cd28558807
Revises: ec1de0eb7243
Create Date: 2025-07-23 02:30:35.773016

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'd3cd28558807'
down_revision: Union[str, None] = 'ec1de0eb7243'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('order_transactions', sa.Column('payment_url', sa.String(), server_default='', nullable=False))
    op.add_column('order_transactions', sa.Column('payment_id', sa.String(), server_default='', nullable=False))
    op.create_unique_constraint(None, 'order_transactions', ['transaction_id'])
    op.create_unique_constraint(None, 'order_transactions', ['payment_id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_transactions', type_='unique')
    op.drop_constraint(None, 'order_transactions', type_='unique')
    op.drop_column('order_transactions', 'payment_id')
    op.drop_column('order_transactions', 'payment_url')
    # ### end Alembic commands ###
