"""customer_multi_signup

Revision ID: db4ec47629f4
Revises: 1f8fe613e5c9
Create Date: 2025-07-20 07:18:31.187451

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'db4ec47629f4'
down_revision: Union[str, None] = '1f8fe613e5c9'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('mess_customer')
    op.add_column('customer', sa.Column('mess_id', sa.UUID(), nullable=False))
    op.drop_index('ix_customer_email', table_name='customer')
    op.create_index(op.f('ix_customer_email'), 'customer', ['email'], unique=False)
    op.create_unique_constraint('unique_customer_mess_email', 'customer', ['mess_id', 'email'])
    op.create_foreign_key(None, 'customer', 'mess', ['mess_id'], ['id'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer', type_='foreignkey')
    op.drop_constraint('unique_customer_mess_email', 'customer', type_='unique')
    op.drop_index(op.f('ix_customer_email'), table_name='customer')
    op.create_index('ix_customer_email', 'customer', ['email'], unique=True)
    op.drop_column('customer', 'mess_id')
    op.create_table('mess_customer',
    sa.Column('mess_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.Column('customer_id', sa.UUID(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['customer_id'], ['customer.id'], name='mess_customer_customer_id_fkey'),
    sa.ForeignKeyConstraint(['mess_id'], ['mess.id'], name='mess_customer_mess_id_fkey')
    )
    # ### end Alembic commands ###
