"""category_update

Revision ID: e167ab91be6e
Revises: ef9eaee6ed04
Create Date: 2025-07-01 01:31:58.505578

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e167ab91be6e'
down_revision: Union[str, None] = 'ef9eaee6ed04'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item_category', sa.Column('image', sa.String(), nullable=True))
    op.add_column('menu_item_category', sa.Column('slug', sa.String(), nullable=False))
    op.create_unique_constraint(None, 'menu_item_category', ['slug'])
    op.drop_column('menu_item_category', 'is_active')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item_category', sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'menu_item_category', type_='unique')
    op.drop_column('menu_item_category', 'slug')
    op.drop_column('menu_item_category', 'image')
    # ### end Alembic commands ###
