"""orders_item_tweak

Revision ID: e1c606f67ab3
Revises: 7c79a745e22d
Create Date: 2025-07-21 02:50:06.505780

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e1c606f67ab3'
down_revision: Union[str, None] = '7c79a745e22d'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.alter_column('order_items', 'menu_item_id',
               existing_type=sa.UUID(),
               nullable=True)
    op.drop_constraint('order_items_menu_item_id_fkey', 'order_items', type_='foreignkey')
    op.create_foreign_key(None, 'order_items', 'menu_item', ['menu_item_id'], ['id'], ondelete='SET NULL')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'order_items', type_='foreignkey')
    op.create_foreign_key('order_items_menu_item_id_fkey', 'order_items', 'menu_item', ['menu_item_id'], ['id'])
    op.alter_column('order_items', 'menu_item_id',
               existing_type=sa.UUID(),
               nullable=False)
    # ### end Alembic commands ###
