"""mess_customer_sec_model

Revision ID: e44ef60b56fd
Revises: 3ccf5c07c723
Create Date: 2025-07-16 00:26:15.021680

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'e44ef60b56fd'
down_revision: Union[str, None] = '3ccf5c07c723'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mess_customer', sa.Column('customer_id', sa.UUID(), nullable=True))
    op.drop_constraint('mess_customer_user_id_fkey', 'mess_customer', type_='foreignkey')
    op.create_foreign_key(None, 'mess_customer', 'customer', ['customer_id'], ['id'])
    op.drop_column('mess_customer', 'user_id')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mess_customer', sa.Column('user_id', sa.UUID(), autoincrement=False, nullable=True))
    op.drop_constraint(None, 'mess_customer', type_='foreignkey')
    op.create_foreign_key('mess_customer_user_id_fkey', 'mess_customer', 'user', ['user_id'], ['id'])
    op.drop_column('mess_customer', 'customer_id')
    # ### end Alembic commands ###
