"""reset

Revision ID: ef9eaee6ed04
Revises: 
Create Date: 2025-06-30 17:37:22.218728

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa
from sqlalchemy.dialects import postgresql

# revision identifiers, used by Alembic.
revision: str = 'ef9eaee6ed04'
down_revision: Union[str, None] = None
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""

    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('menu_item_menu_id_fkey', 'menu_item', type_='foreignkey')
    op.drop_constraint('menu_item_category_menu_id_fkey', 'menu_item_category', type_='foreignkey')
    op.drop_table('menu')
    op.add_column('menu_item', sa.Column('mess_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'menu_item', 'mess', ['mess_id'], ['id'])
    op.drop_column('menu_item', 'menu_id')
    op.add_column('menu_item_category', sa.Column('mess_id', sa.UUID(), nullable=False))
    op.create_foreign_key(None, 'menu_item_category', 'mess', ['mess_id'], ['id'])
    op.drop_column('menu_item_category', 'menu_id')
    op.add_column('menu_item_image', sa.Column('url', sa.String(), nullable=False))
    op.add_column('menu_item_image', sa.Column('path', sa.String(), nullable=False))
    op.drop_column('menu_item_image', 'image')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('menu_item_image', sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=False))
    op.drop_column('menu_item_image', 'path')
    op.drop_column('menu_item_image', 'url')
    op.add_column('menu_item_category', sa.Column('menu_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu_item_category', type_='foreignkey')
    op.create_foreign_key('menu_item_category_menu_id_fkey', 'menu_item_category', 'menu', ['menu_id'], ['id'])
    op.drop_column('menu_item_category', 'mess_id')
    op.add_column('menu_item', sa.Column('menu_id', sa.UUID(), autoincrement=False, nullable=False))
    op.drop_constraint(None, 'menu_item', type_='foreignkey')
    op.create_foreign_key('menu_item_menu_id_fkey', 'menu_item', 'menu', ['menu_id'], ['id'])
    op.drop_column('menu_item', 'mess_id')
    op.create_table('menu',
    sa.Column('id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('title', sa.VARCHAR(), autoincrement=False, nullable=False),
    sa.Column('description', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.Column('mess_id', sa.UUID(), autoincrement=False, nullable=False),
    sa.Column('created_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('updated_at', postgresql.TIMESTAMP(timezone=True), autoincrement=False, nullable=True),
    sa.Column('is_active', sa.BOOLEAN(), autoincrement=False, nullable=True),
    sa.Column('image', sa.VARCHAR(), autoincrement=False, nullable=True),
    sa.ForeignKeyConstraint(['mess_id'], ['mess.id'], name='menu_mess_id_fkey'),
    sa.PrimaryKeyConstraint('id', name='menu_pkey')
    )
    # ### end Alembic commands ###
