"""customer_token_db_update

Revision ID: fd394d50a39f
Revises: 7d3f66be6929
Create Date: 2025-07-16 05:00:41.467797

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd394d50a39f'
down_revision: Union[str, None] = '7d3f66be6929'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint('customer_access_token_user_id_fkey', 'customer_access_token', type_='foreignkey')
    op.create_foreign_key(None, 'customer_access_token', 'customer', ['user_id'], ['id'], ondelete='cascade')
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'customer_access_token', type_='foreignkey')
    op.create_foreign_key('customer_access_token_user_id_fkey', 'customer_access_token', 'user', ['user_id'], ['id'], ondelete='CASCADE')
    # ### end Alembic commands ###
