"""add_slug

Revision ID: fd87b91aa9cf
Revises: 93a6c566a297
Create Date: 2025-06-26 16:35:56.451362

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = 'fd87b91aa9cf'
down_revision: Union[str, None] = '93a6c566a297'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('mess', sa.Column('slug', sa.String(), server_default=sa.text('gen_random_uuid()::text'), nullable=False))
    op.create_unique_constraint(None, 'mess', ['slug'])
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_constraint(None, 'mess', type_='unique')
    op.drop_column('mess', 'slug')
    # ### end Alembic commands ###
