// This file is auto-generated by @hey-api/openapi-ts

/**
 * BearerResponse
 */
export type BearerResponse = {
    /**
     * Access Token
     */
    access_token: string;
    /**
     * Token Type
     */
    token_type: string;
};

/**
 * Body_auth_database_login_auth_login_post
 */
export type BodyAuthDatabaseLoginAuthLoginPost = {
    /**
     * Grant Type
     */
    grant_type?: string | null;
    /**
     * Username
     */
    username: string;
    /**
     * Password
     */
    password: string;
    /**
     * Scope
     */
    scope?: string;
    /**
     * Client Id
     */
    client_id?: string | null;
    /**
     * Client Secret
     */
    client_secret?: string | null;
};

/**
 * Body_reset_forgot_password_auth_forgot_password_post
 */
export type BodyResetForgotPasswordAuthForgotPasswordPost = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_reset_reset_password_auth_reset_password_post
 */
export type BodyResetResetPasswordAuthResetPasswordPost = {
    /**
     * Token
     */
    token: string;
    /**
     * Password
     */
    password: string;
};

/**
 * Body_verify_request_token_auth_request_verify_token_post
 */
export type BodyVerifyRequestTokenAuthRequestVerifyTokenPost = {
    /**
     * Email
     */
    email: string;
};

/**
 * Body_verify_verify_auth_verify_post
 */
export type BodyVerifyVerifyAuthVerifyPost = {
    /**
     * Token
     */
    token: string;
};

/**
 * ErrorModel
 */
export type ErrorModel = {
    /**
     * Detail
     */
    detail: string | {
        [key: string]: string;
    };
};

/**
 * HTTPValidationError
 */
export type HttpValidationError = {
    /**
     * Detail
     */
    detail?: Array<ValidationError>;
};

/**
 * OAuth2AuthorizeResponse
 */
export type OAuth2AuthorizeResponse = {
    /**
     * Authorization Url
     */
    authorization_url: string;
};

/**
 * ResponseMessage
 */
export type ResponseMessage = {
    /**
     * Message
     */
    message: string;
    /**
     * Status Code
     */
    status_code: number;
};

/**
 * UserCreate
 */
export type UserCreate = {
    /**
     * Email
     */
    email: string;
    /**
     * Password
     */
    password: string;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Image
     */
    image?: string | null;
    role?: UserRole | null;
};

/**
 * UserRead
 */
export type UserRead = {
    /**
     * Id
     */
    id: string;
    /**
     * Email
     */
    email: string;
    /**
     * Is Active
     */
    is_active?: boolean;
    /**
     * Is Superuser
     */
    is_superuser?: boolean;
    /**
     * Is Verified
     */
    is_verified?: boolean;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Image
     */
    image?: string | null;
    role?: UserRole;
    /**
     * Created At
     */
    created_at: string;
};

/**
 * UserRole
 */
export type UserRole = 'ADMIN' | 'USER';

/**
 * UserUpdate
 */
export type UserUpdate = {
    /**
     * Password
     */
    password?: string | null;
    /**
     * Email
     */
    email?: string | null;
    /**
     * Is Active
     */
    is_active?: boolean | null;
    /**
     * Is Superuser
     */
    is_superuser?: boolean | null;
    /**
     * Is Verified
     */
    is_verified?: boolean | null;
    /**
     * Name
     */
    name?: string | null;
    /**
     * Image
     */
    image?: string | null;
    role?: UserRole | null;
};

/**
 * ValidationError
 */
export type ValidationError = {
    /**
     * Location
     */
    loc: Array<string | number>;
    /**
     * Message
     */
    msg: string;
    /**
     * Error Type
     */
    type: string;
};

export type AuthDatabaseLoginAuthLoginPostData = {
    body: BodyAuthDatabaseLoginAuthLoginPost;
    path?: never;
    query?: never;
    url: '/auth/login';
};

export type AuthDatabaseLoginAuthLoginPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type AuthDatabaseLoginAuthLoginPostError = AuthDatabaseLoginAuthLoginPostErrors[keyof AuthDatabaseLoginAuthLoginPostErrors];

export type AuthDatabaseLoginAuthLoginPostResponses = {
    /**
     * Successful Response
     */
    200: BearerResponse;
};

export type AuthDatabaseLoginAuthLoginPostResponse = AuthDatabaseLoginAuthLoginPostResponses[keyof AuthDatabaseLoginAuthLoginPostResponses];

export type AuthDatabaseLogoutAuthLogoutPostData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/auth/logout';
};

export type AuthDatabaseLogoutAuthLogoutPostErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type AuthDatabaseLogoutAuthLogoutPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type RegisterRegisterAuthRegisterPostData = {
    body: UserCreate;
    path?: never;
    query?: never;
    url: '/auth/register';
};

export type RegisterRegisterAuthRegisterPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type RegisterRegisterAuthRegisterPostError = RegisterRegisterAuthRegisterPostErrors[keyof RegisterRegisterAuthRegisterPostErrors];

export type RegisterRegisterAuthRegisterPostResponses = {
    /**
     * Successful Response
     */
    201: UserRead;
};

export type RegisterRegisterAuthRegisterPostResponse = RegisterRegisterAuthRegisterPostResponses[keyof RegisterRegisterAuthRegisterPostResponses];

export type OauthGoogleDatabaseAuthorizeAuthGoogleAuthorizeGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Scopes
         */
        scopes?: Array<string>;
    };
    url: '/auth/google/authorize';
};

export type OauthGoogleDatabaseAuthorizeAuthGoogleAuthorizeGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthGoogleDatabaseAuthorizeAuthGoogleAuthorizeGetError = OauthGoogleDatabaseAuthorizeAuthGoogleAuthorizeGetErrors[keyof OauthGoogleDatabaseAuthorizeAuthGoogleAuthorizeGetErrors];

export type OauthGoogleDatabaseAuthorizeAuthGoogleAuthorizeGetResponses = {
    /**
     * Successful Response
     */
    200: OAuth2AuthorizeResponse;
};

export type OauthGoogleDatabaseAuthorizeAuthGoogleAuthorizeGetResponse = OauthGoogleDatabaseAuthorizeAuthGoogleAuthorizeGetResponses[keyof OauthGoogleDatabaseAuthorizeAuthGoogleAuthorizeGetResponses];

export type OauthGoogleDatabaseCallbackAuthGoogleCallbackGetData = {
    body?: never;
    path?: never;
    query?: {
        /**
         * Code
         */
        code?: string | null;
        /**
         * Code Verifier
         */
        code_verifier?: string | null;
        /**
         * State
         */
        state?: string | null;
        /**
         * Error
         */
        error?: string | null;
    };
    url: '/auth/google/callback';
};

export type OauthGoogleDatabaseCallbackAuthGoogleCallbackGetErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type OauthGoogleDatabaseCallbackAuthGoogleCallbackGetError = OauthGoogleDatabaseCallbackAuthGoogleCallbackGetErrors[keyof OauthGoogleDatabaseCallbackAuthGoogleCallbackGetErrors];

export type OauthGoogleDatabaseCallbackAuthGoogleCallbackGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ResetForgotPasswordAuthForgotPasswordPostData = {
    body: BodyResetForgotPasswordAuthForgotPasswordPost;
    path?: never;
    query?: never;
    url: '/auth/forgot-password';
};

export type ResetForgotPasswordAuthForgotPasswordPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetForgotPasswordAuthForgotPasswordPostError = ResetForgotPasswordAuthForgotPasswordPostErrors[keyof ResetForgotPasswordAuthForgotPasswordPostErrors];

export type ResetForgotPasswordAuthForgotPasswordPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type ResetResetPasswordAuthResetPasswordPostData = {
    body: BodyResetResetPasswordAuthResetPasswordPost;
    path?: never;
    query?: never;
    url: '/auth/reset-password';
};

export type ResetResetPasswordAuthResetPasswordPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ResetResetPasswordAuthResetPasswordPostError = ResetResetPasswordAuthResetPasswordPostErrors[keyof ResetResetPasswordAuthResetPasswordPostErrors];

export type ResetResetPasswordAuthResetPasswordPostResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostData = {
    body: BodyVerifyRequestTokenAuthRequestVerifyTokenPost;
    path?: never;
    query?: never;
    url: '/auth/request-verify-token';
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyRequestTokenAuthRequestVerifyTokenPostError = VerifyRequestTokenAuthRequestVerifyTokenPostErrors[keyof VerifyRequestTokenAuthRequestVerifyTokenPostErrors];

export type VerifyRequestTokenAuthRequestVerifyTokenPostResponses = {
    /**
     * Successful Response
     */
    202: unknown;
};

export type VerifyVerifyAuthVerifyPostData = {
    body: BodyVerifyVerifyAuthVerifyPost;
    path?: never;
    query?: never;
    url: '/auth/verify';
};

export type VerifyVerifyAuthVerifyPostErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type VerifyVerifyAuthVerifyPostError = VerifyVerifyAuthVerifyPostErrors[keyof VerifyVerifyAuthVerifyPostErrors];

export type VerifyVerifyAuthVerifyPostResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type VerifyVerifyAuthVerifyPostResponse = VerifyVerifyAuthVerifyPostResponses[keyof VerifyVerifyAuthVerifyPostResponses];

export type UsersCurrentUserUsersMeGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersCurrentUserUsersMeGetErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
};

export type UsersCurrentUserUsersMeGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersCurrentUserUsersMeGetResponse = UsersCurrentUserUsersMeGetResponses[keyof UsersCurrentUserUsersMeGetResponses];

export type UsersPatchCurrentUserUsersMePatchData = {
    body: UserUpdate;
    path?: never;
    query?: never;
    url: '/users/me';
};

export type UsersPatchCurrentUserUsersMePatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchCurrentUserUsersMePatchError = UsersPatchCurrentUserUsersMePatchErrors[keyof UsersPatchCurrentUserUsersMePatchErrors];

export type UsersPatchCurrentUserUsersMePatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchCurrentUserUsersMePatchResponse = UsersPatchCurrentUserUsersMePatchResponses[keyof UsersPatchCurrentUserUsersMePatchResponses];

export type UsersDeleteUserUsersIdDeleteData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersDeleteUserUsersIdDeleteErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersDeleteUserUsersIdDeleteError = UsersDeleteUserUsersIdDeleteErrors[keyof UsersDeleteUserUsersIdDeleteErrors];

export type UsersDeleteUserUsersIdDeleteResponses = {
    /**
     * Successful Response
     */
    204: void;
};

export type UsersDeleteUserUsersIdDeleteResponse = UsersDeleteUserUsersIdDeleteResponses[keyof UsersDeleteUserUsersIdDeleteResponses];

export type UsersUserUsersIdGetData = {
    body?: never;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersUserUsersIdGetErrors = {
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersUserUsersIdGetError = UsersUserUsersIdGetErrors[keyof UsersUserUsersIdGetErrors];

export type UsersUserUsersIdGetResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersUserUsersIdGetResponse = UsersUserUsersIdGetResponses[keyof UsersUserUsersIdGetResponses];

export type UsersPatchUserUsersIdPatchData = {
    body: UserUpdate;
    path: {
        /**
         * Id
         */
        id: string;
    };
    query?: never;
    url: '/users/{id}';
};

export type UsersPatchUserUsersIdPatchErrors = {
    /**
     * Bad Request
     */
    400: ErrorModel;
    /**
     * Missing token or inactive user.
     */
    401: unknown;
    /**
     * Not a superuser.
     */
    403: unknown;
    /**
     * The user does not exist.
     */
    404: unknown;
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type UsersPatchUserUsersIdPatchError = UsersPatchUserUsersIdPatchErrors[keyof UsersPatchUserUsersIdPatchErrors];

export type UsersPatchUserUsersIdPatchResponses = {
    /**
     * Successful Response
     */
    200: UserRead;
};

export type UsersPatchUserUsersIdPatchResponse = UsersPatchUserUsersIdPatchResponses[keyof UsersPatchUserUsersIdPatchResponses];

export type ReadRootGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/';
};

export type ReadRootGetResponses = {
    /**
     * Successful Response
     */
    200: ResponseMessage;
};

export type ReadRootGetResponse = ReadRootGetResponses[keyof ReadRootGetResponses];

export type HealthCheckHealthGetData = {
    body?: never;
    path?: never;
    query?: never;
    url: '/health';
};

export type HealthCheckHealthGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ReadItemItemsItemIdGetData = {
    body?: never;
    path: {
        /**
         * Item Id
         */
        item_id: number;
    };
    query?: {
        /**
         * Q
         */
        q?: string | null;
    };
    url: '/items/{item_id}';
};

export type ReadItemItemsItemIdGetErrors = {
    /**
     * Validation Error
     */
    422: HttpValidationError;
};

export type ReadItemItemsItemIdGetError = ReadItemItemsItemIdGetErrors[keyof ReadItemItemsItemIdGetErrors];

export type ReadItemItemsItemIdGetResponses = {
    /**
     * Successful Response
     */
    200: unknown;
};

export type ClientOptions = {
    baseURL: 'http://127.0.0.1:8000' | (string & {});
};